# Config file for automatic testing at travis-ci.org

language: python

python:
    - "3.6"
    - "3.5"
    - "3.4"
    - "3.3"

install:
    - pip install pytest
    - pip install codecov
    - pip install coverage

script:
    - py.test
    - coverage run --source autolearn -m pytest

after_success:
    - codecov

#deploy:
#  provider: pypi
#  distributions: sdist bdist_wheel
#  user: austinmcconnell
#  password:
#    secure: PLEASE_REPLACE_ME
#  on:
#    tags: true
#    repo: austinmcconnell/autolearn
#    condition: py35
